### ISSUE TITLE
math domain error

### ISSUE THREAD

**Issue by sowish** [jason2506/PythonHMM#1]
can you explain the problem for me ? I used the train function of the project, but  it alway has math errors.
![1](https://cloud.githubusercontent.com/assets/8122929/23549413/29b70012-0047-11e7-9a15-a927d71d3a4d.png)
And I want to use the given state sequence and observation sequence to train the parameters of HMM.
My codes are as  fellows:

```python
# -*- coding: utf-8 -*-

import hmm

state1 = 'AAABNA'
state2= 'AAABNA'
state3= 'AAABNA'
symbol_list1 = [1,2,3,'a','.',1]
symbol_list2 = [1,3,2,'a','.',3]
symbol_list3 = [2,1,1,'a','.',1]
sequences = [(state1, symbol_list1),(state2, symbol_list2),(state3, symbol_list3)]
model = hmm.train(sequences)
print model._trans_prob
```

**Comment by jason2506** [comment]
The reason is that `model.evaluate()` may results zero probability in some cases.

Such situation can be avoided with `smoothing` parameter of `hmm.train()`.

For instance:

```python
model = hmm.train(sequences, smoothing=1e-10)
```

**Comment by sowish** [comment]
Thanks a lot for your help! It does work.

**Comment by sowish** [comment]
Thanks for your answer  before. I am  so sorry ,bu this is another a question of the emit_prob which was estimated by given data. My codes are as blow.
```
import hmm
state1 = ['A','A','N','B']
state2= ['A','B','N','B']
symbol_list1 = [1,1,'.','c']
symbol_list2 = [2,'a','.','a']
sequences = [(state1, symbol_list1),(state2, symbol_list2)]
model = hmm.train(sequences,smoothing=1e-10)
print ' trans_prob---------------------------------'
print model._trans_prob
print ' start_prob---------------------------------'
print model._start_prob
print ' emit_prob---------------------------------'
print model._emit_prob
print ' ---------------------------------'
print model.evaluate([1,1,'.','c'])
```
A is the state of numbers  , B is the state of  letters and N means the characters. And the estimated parameters are as blow.
![qq 20170303214221](https://cloud.githubusercontent.com/assets/8122929/23553108/3f4ef2be-005a-11e7-9377-7fe04ee277d0.png)

It is  clear that trans_prob and start_prob are right.But emit_prob my be not right, for example, the  probability of A to a should nearly  be  zero.

**Comment by jason2506** [comment]
Hmm....there may be some calculation errors in my program. But I need some time to check it out (it was written in so many years ago).

**Comment by sowish** [comment]
I get it. If you fix these errors, can you let me know by giving a comment here? Thank you very much!

**Comment by jason2506** [comment]
Finally, I figured out that the issue is caused by size of data instead of calculation error.

In current implementation, training data is fit into model one after the other: the model will take first sequence (pair of states and symbols), re-estimate the probabilities according to it, and then take the next one.

In your case above, `A`s in the first sequence `(state1, symbol_list1)` are never followed by `B`, and hance the model considered that `A` is not possible to be transited to `B`.

Besides, symbol `1` is never emitted in the second sequence `(state2, symbol_list2)`, which causes underestimation of emission probabilities of `1`.

The root of problem is, your training data is not enough to estimate accurate probabilities. I think increasing the data size will fix the problem.

**Comment by jason2506** [comment]
Finally, I figured out that the issue is caused by the data.

In current implementation, training data is passed into model one after the other: the model will take first sequence (pair of states and symbols), re-estimate the probabilities according to it, and then take the next one.

In your case above, `A`s in the first sequence `(state1, symbol_list1)` are never followed by `B`, and hance the model considered that `A` is not possible to be transited to `B`.

Besides, symbol `1` is never emitted in the second sequence `(state2, symbol_list2)`, which causes underestimation of emission probabilities of `1`.

Such biased cases need to be "correct" with other data. However, your training data is not enough to estimate accurate probabilities. I think increasing the data size may fix the problem.

**Comment by jason2506** [comment]
By the way, I must to inform you that this project is just a toy (as an exercise for learning HMMs and Python).

If you want to use it in some real-world problem, I would seriously suggest you to use more carefully implemented library (e.g., [seqlearn](https://github.com/larsmans/seqlearn)).

**Comment by sowish** [comment]
Thanks  for your answering patiently.I will seriously consider your suggestion.
